### ISSUE TITLE
Uploading big file to imagej.net server fails

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej-plugins-uploader-webdav#5]
[The test uploading bigger files](https://github.com/imagej/imagej-plugins-uploader-webdav/blob/master/src/test/java/net/imagej/plugins/uploaders/webdav/WebDAVUploaderTests.java#L129-L142) currently throws a `SocketException` for `https:sites.imagej.net`, but works for `http://sites.imagej.net` update sites. It also works via HTTPS and the MPI-CBG server update sites. The request timeout happens when the upload stream is done processing.

Here is a log from a user using the updater ([forum post](https://forum.image.sc/t/cant-upload-large-jar/28919)):
```
[ERROR] null
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at net.imagej.plugins.uploaders.webdav.WebDAVUploader.runMethodOnClient(WebDAVUploader.java:525)
	at net.imagej.plugins.uploaders.webdav.WebDAVUploader.upload(WebDAVUploader.java:287)
	at net.imagej.plugins.uploaders.webdav.WebDAVUploader.upload(WebDAVUploader.java:231)
	at net.imagej.updater.FilesUploader.upload(FilesUploader.java:260)
	at net.imagej.ui.swing.updater.UpdaterFrame.upload(UpdaterFrame.java:805)
	at net.imagej.ui.swing.updater.UpdaterFrame$5$1.run(UpdaterFrame.java:311)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 8 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at sun.security.ssl.OutputRecord.writeBuffer(Unknown Source)
	at sun.security.ssl.OutputRecord.write(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:169)
	at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:124)
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
	at net.imagej.plugins.uploaders.webdav.ProgressHttpEntityWrapper$ProgressFilterOutputStream.write(ProgressHttpEntityWrapper.java:108)
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:146)
	at net.imagej.plugins.uploaders.webdav.ProgressHttpEntityWrapper.writeTo(ProgressHttpEntityWrapper.java:90)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	... 10 more
```
This is what I get from the test: 
```
[DEBUG] Response: 408 HTTP/1.1 408 Request Timeout
[DEBUG] Header: Date = Thu, 22 Aug 2019 22:07:59 GMT
[DEBUG] Header: Server = Apache/2.4.18 (Ubuntu)
[DEBUG] Header: Content-Length = 304
[DEBUG] Header: Connection = close
[DEBUG] Header: Content-Type = text/html; charset=iso-8859-1
```

@ctrueden @turekg Did anything change on the server in the last weeks which could be relevant here? I was able to run these tests successfully in the past for both HTTP and HTTPS. The implementation on our side does not distinguish between HTTP and HTTPS. 

Searching lead me to [this post](https://stackoverflow.com/a/39143718/5325168): 
> In most cases this can be caused either by the timeout issue (e.g. the response takes too much time or server is overloaded with the requests), **or the client sent the SYN, but it didn't receive ACK (acknowledgment of the connection termination)**.

Got a bit more SYN / ACK context [here](https://stackoverflow.com/a/54515836/5325168).

Tomorrow at the institute I can have a closer look at the logs.

**Comment by turekg** [comment]
Is this happening all the time, or once in a while?

**Comment by salimkanoun** [comment]
all the time, it is easy to reproduce

**Comment by frauzufall** [comment]
We adjusted the server configuration and my tests run successfully. Let me know if you are still experiencing issues.
